import Head from 'next/head'

import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import jwtDecode from 'jwt-decode'
import Footer from './components/Footer'
import setUserInfo from './helpers/token'
import { useState,useEffect } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let userinfo;
  const [mounted,setMounted]=useState(false)

  useEffect((userinfo) => {
    setMounted(true)
    if (localStorage.token) {
      const jwt = localStorage.getItem("token");
      setUserInfo(jwt);
      userinfo = jwtDecode(jwt);
      console.log(userinfo)
      console.log(userinfo.id)
    
  }
   


  }, []); 
  if (mounted){
    if (localStorage.token) {
      const jwt = localStorage.getItem("token");
      setUserInfo(jwt);
      userinfo = jwtDecode(jwt);
      console.log(userinfo)
      console.log(userinfo.id)
    
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <Navbar/>
       <div className='all'>
        <div className='hero'> 
      <img src='./hero.jpg'/>
      <h1><span style={{color:'#FFA712'}}>LabSpace</span> - лучшее пространство для студентов</h1>
        </div>
        <div style={{display:'flex', justifyContent:'space-between',marginTop:20, gap:20,fontStyle:'italic'}}>
        <div style={{display:'flex', gap:20}}>
        <img  className='hero-small' src='./computer.png'/>

          <span className='hero-span'>Онлайн учебно-методический комплекс доступен всегда, где бы вы ни находились. Вы можете использовать его на компьютере, планшете или смартфоне.</span>
          </div>
 
       <div style={{display:'flex', gap:20}}>
       <img className='hero-small' src='./growth.png'/>

          <span className='hero-span'>С помощью нашей платформы вы сможете быстрее достигать своих целей</span>

          </div>
          <div style={{display:'flex', gap:20}}>
       <img className='hero-small' src='./rest.png'/>

          <span className='hero-span'>Комфортные условия обучения и работы</span>

          </div>
          <div style={{display:'flex', gap:20}}>
       <img className='hero-small' src='./free.png'/>

          <span className='hero-span'>Все возможности платформы бесплатны</span>

          </div>
      
       </div>

       </div>
       <Footer/>

      </main>

    </>
  )
}
else{
  return null
}
}